### ISSUE TITLE
nuxt generate always calls api multiple times

### ISSUE THREAD

**Issue by gabrielsze** [nuxt-community/prismic-module#134]
A reference to an issue raised earlier here - https://github.com/nuxt-community/prismic-module/issues/77,
especially highlighted in this comment

> I am only including the plugin in modules of nuxt config and my app is universal. Not all the pages are using this plugin, only one page called /blog. Even the root of the website is blocked when there is no prismic related calls in index file. To init the API on load I tried to inject it as plugin instead of using in modules (the Vue way) but then it is not available for the server side rendering.

This is an issue for me because I'm only utilising prismic in one of my subdirectories `example.com/blog`. However, when I generate many other pages in other subdirectories `example.com/pages1`,`example.com/pages2` etc, the prismic API key is somehow always called, resulting in many API calls incurred (thousands of pages generated), and this error is thrown many times.

```
 ERROR  Failed to init Prismic API, preventing app fatal error.                            23:26:10


 ERROR  request to https://<REPO NAME>.cdn.prismic.io/api/v2?routes=%5B%7B%22type%22%3A%22post%22%2C%22path%22%3A%22%2Fblog%2F%3Auid%22%7D%5D failed, reason: write EPROTO 4534230528:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:


  
  at ClientRequest.<anonymous> (node_modules/node-fetch/lib/index.js:1461:11)
  at ClientRequest.emit (events.js:311:20)
  at ClientRequest.EventEmitter.emit (domain.js:482:12)
  at TLSSocket.socketErrorListener (_http_client.js:426:9)
  at TLSSocket.emit (events.js:311:20)
  at TLSSocket.EventEmitter.emit (domain.js:482:12)
  at errorOrDestroy (internal/streams/destroy.js:108:12)
  at onwriteError (_stream_writable.js:462:5)
  at onwrite (_stream_writable.js:483:5)
  at internal/streams/destroy.js:50:7
  at TLSSocket.Socket._destroy (net.js:673:5)
  at TLSSocket.destroy (internal/streams/destroy.js:38:8)
  at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:93:12)
``` 

Is there a way to **only include the API calls for pages which only require them**?

**Comment by lihbr** [comment]
Hey @gabrielsze, thanks for raising your concerns regarding that and taking the time to look for duplicates.

As of writing this there's unfortunately no way to achieve that using this module.

A workaround would be to scale down to @prismicio/vue which might give you more control but might not be as straightforward to use as this module.

However with the new version of @prismicio/client we're now recommending to init the API through the .client method that comes with the benefit initing the API only when needed. We'll check if that's possible to migrate this module API init process to this method without introducing breaking changes.

Let us know if anything!

**Comment by lihbr** [comment]
*Update `05/04/2021`:*
1. I attempted to migrate the API init process to `.client` while working on #137. Unfortunately, I discovered a lot of small breaking changes related to this refactor, it mainly changes the way to access the internals of the client (see: https://github.com/prismicio/prismic-javascript/blob/HEAD/src/ResolvedApi.ts#L55-L64) which might cause trouble to some users. This will be part of the module v2 though after we're done refreshing @prismicio/client: https://github.com/prismicio/prismic-javascript/issues/163

**Comment by lihbr** [comment]
Just updated my previous comment as I had an idea about it, landing soon 🙂
